# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab2_code_for_cadets/Lab2.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# XDC: c:/Users/C27Bradford.Hurt/ece383_wksp/lab4/Lab4.gen/sources_1/bd/design_1/design_1_ooc.xdc
